#!/bin/bash
# Before suspension, dumps the last 3 minutes of journalctl, and the last 30
# lines of Xorg.log and of .xsession.error and the output of xrandr into
# ~/debug_x directory

# Get the user name. It assumes a single user
user=`users | sed 's: :\n:g' | uniq`
# home directory and directory where to save the log files 
homedir=/home/$user
debug_dir=$homedir/debug_x

if [ ! -e $debug_dir ]
then
    exit 0
fi

case $1/$2 in
  pre/*)
    echo "saving the journal, xorg log, xsession error and xrandr output in $homedir for debugging"
    journalctl --since "3 minutes ago" > $debug_dir/journal
    tail -n30 /var/log/Xorg.0.log > $debug_dir/xorg.log
    tail -n30 $homedir/.xsession-errors > $debug_dir/xsession_error
    # set up the x stuff needed by xrandr
    export XAUTHORITY=$homedir/.Xauthority
    export DISPLAY=:0
    xrandr --verbose > $debug_dir/xrandr.out
    ;;
  post/*)
      # nothing to be done
    ;;
esac
