#!/bin/bash
# Before suspension, dumps into ~/debug_x directory:
# * the last 3 minutes of journalctl
# * the last 30 lines of Xorg.log and of .xsession.error
# * the output of xrandr
# * ps -e

# Get the user name. It assumes a single user
user=`users | sed 's: :\n:g' | uniq`
# home directory and directory where to save the log files 
homedir=/home/$user
debug_dir=$homedir/debug_x

if [ ! -e $debug_dir ]
then
    exit 0
fi

case $1/$2 in
  pre/*)
    echo "saving the journal, xorg log, xsession error and xrandr output in $homedir for debugging"
    journalctl --since "3 minutes ago" > $debug_dir/journal.out
    for xlog in /var/log/Xorg.0.log*
    do
        if [ -s $xlog ]
        then
            cp -a $xlog $debug_dir
        fi
    done
    for xsession in $homedir/.xsession-errors* 
    do
        if [ -s $xsession ]
        then
            fname=`basename $xsession`
            cp -a $xsession $debug_dir/${fname/.}
        fi
    done
    # set up the x stuff needed by xrandr
    export XAUTHORITY=$homedir/.Xauthority
    export DISPLAY=:0
    xrandr --verbose > $debug_dir/xrandr.out
    # dump list of running
    ps -ef > $debug_dir/ps_ef.out
    ;;
  post/*)
      # nothing to be done
    ;;
esac
