#!/bin/bash
# virtualenvwrapper
# This hook is sourced after a new virtualenv is activated.
# link pyqt 4, 5 and sip into the virtualenv

# get the python version
pyv=`python -c 'import sys; print("{}.{}".format(*sys.version_info))'`

virtual_env=${VIRTUAL_ENV}

# get out of the virtual environment
deactivate

python$pyv $WORKON_HOME/postmkvirtualenv.py ${virtual_env}

workon `basename $virtual_env`
